name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./...
    
    - name: Build for all platforms
      run: |
        mkdir -p build
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o build/resolve-transcoder-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -ldflags "-s -w" -o build/resolve-transcoder-windows-arm64.exe .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o build/resolve-transcoder-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o build/resolve-transcoder-darwin-arm64 .
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o build/resolve-transcoder-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o build/resolve-transcoder-linux-arm64 .
    
    - name: Create release packages
      run: |
        mkdir -p release
        
        # Windows packages
        cd build && zip ../release/resolve-transcoder-${{ github.ref_name }}-windows-amd64.zip resolve-transcoder-windows-amd64.exe ../README.md ../LICENSE && cd ..
        cd build && zip ../release/resolve-transcoder-${{ github.ref_name }}-windows-arm64.zip resolve-transcoder-windows-arm64.exe ../README.md ../LICENSE && cd ..
        
        # macOS packages  
        tar -czf release/resolve-transcoder-${{ github.ref_name }}-darwin-amd64.tar.gz -C build resolve-transcoder-darwin-amd64 -C .. README.md LICENSE
        tar -czf release/resolve-transcoder-${{ github.ref_name }}-darwin-arm64.tar.gz -C build resolve-transcoder-darwin-arm64 -C .. README.md LICENSE
        
        # Linux packages
        tar -czf release/resolve-transcoder-${{ github.ref_name }}-linux-amd64.tar.gz -C build resolve-transcoder-linux-amd64 -C .. README.md LICENSE
        tar -czf release/resolve-transcoder-${{ github.ref_name }}-linux-arm64.tar.gz -C build resolve-transcoder-linux-arm64 -C .. README.md LICENSE
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
